# TravisCI build scipt for Cadex OS

os: linux # We don't want to build on Windows!
dist: bionic # We want Ubuntu Bionic Beaver!
sudo: required # Ahoy root! We need you!

language: c # It's all we want (Some apps are in C++, but nevermind!)

compiler: gcc # Aha, gcc

before_install:
    # Install required tools!
    - sudo apt-get install -y mkisofs dosfstools libc6-dev-i386 grub-common xorriso
	# Give the permission to execute that!
	- chmod scripts/build-toolchain.sh +x
    # Be sure to tell the CI to build the toolchain!
    - ./scripts/build-toolchain.sh

script:
    # And finally, build the source!
    - make
